apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: x
  description: Py-Twitter
    This service provides the entry point to the currency exchange
    functionalities.
  annotations:
    github.com/project-slug: MolkoBelen/Py-Twitter
spec:
  type: service
  lifecycle: production
  owner: BICE Connect
