apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Py-Twitter
  annotations:
    github.com/project-slug: MolkoBelen/Py-Twitter
spec:
  type: other
  lifecycle: unknown
  owner: guests
