apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Py-Twitter
  description: |
    This service provides the entry point to the currency exchange
    functionalities.
  annotations:
    github.com/project-slug: MolkoBelen/Py-Twitter
    backstage.io/api-docs: url:https://github.com/MolkoBelen/Py-Twitter/blob/master/swagger.yaml
  system: FX 
spec:
  type: service
  lifecycle: production
  owner: BICE Connect
